# Use an official OpenJDK image as the base image
FROM openjdk:17-jdk-alpine

# Copy the JAR file generated by Maven into the Docker image
ADD target/tp-foyer-5.0.0.jar tp-foyer-5.0.0.jar

# Expose the application port
EXPOSE 8089
#8090
# Run the JAR file
ENTRYPOINT ["java","-jar","/tp-foyer-5.0.0.jar"]

