version: '3.8'

services:
  tp-foyer-app:
    image: mohamedtrabelsi01/devops:101
    ports:
      - "8089:8089"
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/db?createDatabaseIfNotExist=true  # Use service name for DB
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_JPA_SHOW_SQL: 'true'
        SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
        SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: 'true'
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
