version: "3.9"
services:
  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=db
    ports:
      - "3309:3306"
    restart: unless-stopped

  projet_final:
    container_name: tp-foyer-5.0.0
    build: .
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/db?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    image: tp-foyer-5.0.0:1.0
    depends_on:
      - db-mysql
